version: '3'
services:
  windows:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: windows
    environment:
      VERSION: "10"
      USERNAME: "USERNAME"
      PASSWORD: "PASSWORD"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "400G"
      DISK2_SIZE: "100G"
    ports:
      - "8006:8006"
      - "3389:3389"
    volumes:
      - windows-storage:/storage
    stop_grace_period: 2m

volumes:
  windows-storage:
